const { Op } = require('sequelize');
const { Invoice, InvoiceItem, InvoicePayment, Company, User, Payroll, Claim, Project } = require('../models');
const invoiceService = require('../services/invoiceService');
const lhdnService = require('../services/lhdnService');
const invoicePdfService = require('../services/invoicePdfService');
const invoiceExtractionService = require('../services/invoiceExtractionService');
const notificationService = require('../services/notificationService');
const auditService = require('../services/auditService');
const logger = require('../utils/logger');

// ─── CRUD ──────────────────────────────────────────────────────

// Expand a raw PO string into candidates to try matching. Includes the WHOLE
// string first (so single POs containing slashes like "AEM/BD/PO/25/006" match
// as-is) plus split fragments (so multi-PO joins like "PO-001/PO-002" each
// resolve individually).
function expandPoFragments(raw) {
  const cleaned = String(raw || '').trim();
  if (!cleaned) return [];
  const out = [cleaned];
  cleaned
    .replace(/\s+and\s+/gi, '/')
    .split(/[\/,;&|+\s]+/)
    .forEach(p => {
      const t = p.trim();
      if (t && t !== cleaned) out.push(t);
    });
  return out;
}

// Fetch every project's po_number for the company and build a normalized lookup
// map. Normalization = trim + lowercase, so DB collation/case differences don't
// silently break matching.
async function buildPoLookupMap(companyId) {
  const all = await Project.findAll({
    where: { company_id: companyId, po_number: { [Op.not]: null } },
    attributes: ['id', 'public_id', 'code', 'name', 'client_name', 'po_number', 'currency']
  });
  const map = new Map();
  for (const p of all) {
    const key = (p.po_number || '').trim().toLowerCase();
    if (key) map.set(key, p);
  }
  return map;
}

// Batch-resolve project_id for each line item by looking up its po_number
// in the projects table. One DB roundtrip regardless of item count.
async function attachItemProjectIds(items, companyId) {
  const lookup = await buildPoLookupMap(companyId);
  if (lookup.size === 0) return items;

  return items.map(it => {
    for (const candidate of expandPoFragments(it.po_number)) {
      const project = lookup.get(candidate.trim().toLowerCase());
      if (project) return { ...it, project_id: project.id };
    }
    return it;
  });
}

// After invoice-level project_id is finalized, backfill items that still have
// no project_id (typically because the PDF only had a header PO and the AI
// didn't repeat it per-line). This makes the per-project rollup queries work
// correctly — every line of a single-PO invoice gets attributed to its project.
function inheritInvoiceProjectIdToItems(items, invoiceProjectId) {
  if (!invoiceProjectId) return items;
  return items.map(it => it.project_id ? it : { ...it, project_id: invoiceProjectId });
}

// Use the caller-provided invoice number if it's non-empty AND unique within
// the company; otherwise fall back to the auto-generated running number.
async function resolveInvoiceNumber(requested, companyId) {
  const candidate = (requested || '').trim();
  if (candidate) {
    const existing = await Invoice.findOne({
      where: { invoice_number: candidate, company_id: companyId },
      attributes: ['id']
    });
    if (!existing) return { invoiceNumber: candidate, autoGenerated: false };
    // Collision — fall through to auto-gen
    logger.info('Invoice number collision, falling back to auto-gen', { requested: candidate });
  }
  const generated = await invoiceService.generateInvoiceNumber(companyId);
  return { invoiceNumber: generated, autoGenerated: true };
}

/**
 * POST /api/invoices — Create a new invoice with items
 */
const createInvoice = async (req, res, next) => {
  try {
    const { items: rawItems, ...invoiceData } = req.body;
    const companyId = req.user.company_id;
    const userId = req.user.id;

    if (!rawItems || rawItems.length === 0) {
      return res.status(400).json({ success: false, message: 'At least one line item is required' });
    }

    const { invoiceNumber } = await resolveInvoiceNumber(invoiceData.invoice_number, companyId);

    // Calculate item totals
    const calculatedItems = rawItems.map((item, idx) =>
      invoiceService.calculateItemTotals({ ...item, item_number: idx + 1 })
    );
    const totals = invoiceService.calculateInvoiceTotals(calculatedItems);

    // Resolve per-line project_id from po_number lookups
    let itemsWithProjects = await attachItemProjectIds(calculatedItems, companyId);

    // Derive invoice-level project_id: explicit value wins, otherwise inherit
    // from the first line item that has one (the "primary" project).
    if (!invoiceData.project_id) {
      const firstItemProjectId = itemsWithProjects.find(it => it.project_id)?.project_id;
      if (firstItemProjectId) invoiceData.project_id = firstItemProjectId;
    }

    // Backfill any items still missing project_id from the invoice-level one
    itemsWithProjects = inheritInvoiceProjectIdToItems(itemsWithProjects, invoiceData.project_id);

    // 'Recorded' = manually logged for record-keeping (skips the LHDN workflow);
    // 'Pending'  = approved & ready for LHDN submission; otherwise a plain Draft.
    const initialStatus = invoiceData.status === 'Recorded' ? 'Recorded'
      : invoiceData.status === 'Pending' ? 'Pending' : 'Draft';

    const invoice = await Invoice.create({
      ...invoiceData,
      company_id: companyId,
      invoice_number: invoiceNumber,
      ...totals,
      balance_due: totals.total_amount,
      source_type: invoiceData.source_type || 'manual',
      status: initialStatus,
      created_by: userId
    });

    await InvoiceItem.bulkCreate(
      itemsWithProjects.map(item => ({ ...item, invoice_id: invoice.id }))
    );

    if (invoiceData.status === 'Pending') {
      invoice.approved_by = userId;
      invoice.approved_at = new Date();
      await invoice.save();
    }

    const result = await Invoice.findByPk(invoice.id, {
      include: [
        { model: InvoiceItem, as: 'items' },
        { model: User, as: 'creator', attributes: ['id', 'email'] }
      ]
    });

    res.status(201).json({
      success: true,
      message: 'Invoice created successfully',
      data: result
    });
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/invoices — List invoices with pagination, filters, search
 */
const getAllInvoices = async (req, res, next) => {
  try {
    const companyId = req.user.company_id;
    const {
      page = 1, limit = 20,
      status, invoice_type, is_self_billed, project_id,
      search, date_from, date_to,
      sort = 'created_at', order = 'DESC'
    } = req.query;

    const where = { company_id: companyId };

    if (status) {
      where.status = { [Op.in]: status.split(',') };
    }
    if (invoice_type) {
      where.invoice_type = invoice_type;
    }
    if (is_self_billed !== undefined) {
      where.is_self_billed = is_self_billed === 'true';
    }
    if (project_id) {
      where.project_id = project_id;
    }
    if (search) {
      where[Op.or] = [
        { invoice_number: { [Op.iLike]: `%${search}%` } },
        { title: { [Op.iLike]: `%${search}%` } },
        { supplier_name: { [Op.iLike]: `%${search}%` } },
        { buyer_name: { [Op.iLike]: `%${search}%` } }
      ];
    }
    if (date_from || date_to) {
      where.invoice_date = {};
      if (date_from) where.invoice_date[Op.gte] = date_from;
      if (date_to) where.invoice_date[Op.lte] = date_to;
    }

    const offset = (parseInt(page) - 1) * parseInt(limit);
    const allowedSortFields = ['created_at', 'invoice_date', 'invoice_number', 'total_amount', 'status'];
    const sortField = allowedSortFields.includes(sort) ? sort : 'created_at';
    const sortOrder = order.toUpperCase() === 'ASC' ? 'ASC' : 'DESC';

    const { count, rows } = await Invoice.findAndCountAll({
      where,
      include: [
        { model: User, as: 'creator', attributes: ['id', 'email'] },
        { model: Project, as: 'project', attributes: ['id', 'public_id', 'code', 'name', 'po_number'] }
      ],
      order: [[sortField, sortOrder]],
      limit: parseInt(limit),
      offset,
      distinct: true
    });

    res.json({
      success: true,
      data: {
        invoices: rows,
        pagination: {
          page: parseInt(page),
          limit: parseInt(limit),
          totalItems: count,
          totalPages: Math.ceil(count / parseInt(limit))
        }
      }
    });
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/invoices/:id — Get invoice detail with items and payments
 */
const getInvoiceById = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id },
      include: [
        {
          model: InvoiceItem,
          as: 'items',
          order: [['item_number', 'ASC']],
          include: [{ model: Project, as: 'project', attributes: ['id', 'public_id', 'code', 'name'] }]
        },
        { model: InvoicePayment, as: 'payments', include: [{ model: User, as: 'recorder', attributes: ['id', 'email'] }] },
        { model: User, as: 'creator', attributes: ['id', 'email'] },
        { model: User, as: 'approver', attributes: ['id', 'email'] },
        { model: User, as: 'canceller', attributes: ['id', 'email'] },
        { model: Project, as: 'project', attributes: ['id', 'public_id', 'code', 'name', 'client_name', 'po_number'] }
      ]
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    res.json({ success: true, data: invoice });
  } catch (error) {
    next(error);
  }
};

/**
 * PUT /api/invoices/:id — Update invoice (Draft/Invalid only)
 */
const updateInvoice = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id }
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    if (!['Draft', 'Invalid', 'Recorded'].includes(invoice.status)) {
      return res.status(400).json({ success: false, message: 'Only Draft, Invalid or Recorded invoices can be edited' });
    }

    const { items: rawItems, ...invoiceData } = req.body;
    // Invoice number is immutable after creation — strip to prevent overwrite.
    delete invoiceData.invoice_number;

    if (rawItems && rawItems.length > 0) {
      // Replace all items
      await InvoiceItem.destroy({ where: { invoice_id: invoice.id } });

      const calculatedItems = rawItems.map((item, idx) =>
        invoiceService.calculateItemTotals({ ...item, item_number: idx + 1 })
      );
      let itemsWithProjects = await attachItemProjectIds(calculatedItems, invoice.company_id);
      const totals = invoiceService.calculateInvoiceTotals(itemsWithProjects);
      if (!invoiceData.project_id) {
        const firstItemProjectId = itemsWithProjects.find(it => it.project_id)?.project_id;
        if (firstItemProjectId) invoiceData.project_id = firstItemProjectId;
      }
      itemsWithProjects = inheritInvoiceProjectIdToItems(itemsWithProjects, invoiceData.project_id);

      await InvoiceItem.bulkCreate(
        itemsWithProjects.map(item => ({ ...item, invoice_id: invoice.id }))
      );

      Object.assign(invoiceData, totals);
      invoiceData.balance_due = totals.total_amount - parseFloat(invoice.amount_paid || 0);
    }

    // Reset invalid status back to Draft on edit
    if (invoice.status === 'Invalid') {
      invoiceData.status = 'Draft';
      invoiceData.lhdn_validation_errors = null;
    }

    invoiceData.updated_by = req.user.id;
    await invoice.update(invoiceData);

    const result = await Invoice.findByPk(invoice.id, {
      include: [
        { model: InvoiceItem, as: 'items' },
        { model: User, as: 'creator', attributes: ['id', 'email'] }
      ]
    });

    res.json({ success: true, message: 'Invoice updated successfully', data: result });
  } catch (error) {
    next(error);
  }
};

/**
 * DELETE /api/invoices/:id — Delete invoice (Draft only)
 */
const deleteInvoice = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id }
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    if (!['Draft', 'Recorded'].includes(invoice.status)) {
      return res.status(400).json({ success: false, message: 'Only Draft or Recorded invoices can be deleted' });
    }

    await invoice.destroy(); // CASCADE deletes items and payments
    res.json({ success: true, message: 'Invoice deleted successfully' });
  } catch (error) {
    next(error);
  }
};

/**
 * POST /api/invoices/bulk-delete — Delete multiple invoices (Draft/Recorded only)
 */
const bulkDelete = async (req, res, next) => {
  try {
    const { invoice_ids } = req.body;
    if (!invoice_ids || invoice_ids.length === 0) {
      return res.status(400).json({ success: false, message: 'No invoice IDs provided' });
    }

    const invoices = await Invoice.findAll({
      where: {
        public_id: { [Op.in]: invoice_ids },
        company_id: req.user.company_id
      }
    });

    const deleted = [];
    const skipped = [];

    for (const invoice of invoices) {
      if (!['Draft', 'Recorded'].includes(invoice.status)) {
        skipped.push({ invoice_number: invoice.invoice_number, reason: `Status is ${invoice.status}` });
        continue;
      }
      await invoice.destroy(); // CASCADE deletes items and payments
      deleted.push(invoice.invoice_number);
    }

    const notFound = invoice_ids.length - invoices.length;
    if (notFound > 0) {
      skipped.push({ message: `${notFound} invoice(s) not found` });
    }

    res.json({
      success: true,
      message: `${deleted.length} invoice(s) deleted${skipped.length > 0 ? `, ${skipped.length} skipped` : ''}`,
      data: { deleted, skipped }
    });
  } catch (error) {
    next(error);
  }
};

// ─── Workflow Actions ──────────────────────────────────────────

/**
 * PATCH /api/invoices/:id/approve — Draft → Pending
 */
const approveInvoice = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id }
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    if (invoice.status !== 'Draft') {
      return res.status(400).json({ success: false, message: 'Only Draft invoices can be approved' });
    }

    await invoice.update({
      status: 'Pending',
      approved_by: req.user.id,
      approved_at: new Date()
    });

    auditService.log({
      action: 'invoice_approved',
      userId: req.user.id,
      companyId: req.user.company_id,
      targetType: 'Invoice',
      targetId: invoice.id,
      details: { invoice_number: invoice.invoice_number }
    });

    res.json({ success: true, message: 'Invoice approved and ready for LHDN submission', data: invoice });
  } catch (error) {
    next(error);
  }
};

/**
 * POST /api/invoices/:id/submit — Pending → Submitted (calls LHDN)
 */
const submitToLhdn = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id },
      include: [{ model: InvoiceItem, as: 'items' }]
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    if (invoice.status !== 'Pending') {
      return res.status(400).json({ success: false, message: 'Only Pending invoices can be submitted to LHDN' });
    }

    const result = await lhdnService.submitDocument(invoice.toJSON(), invoice.items.map(i => i.toJSON()));

    if (result.acceptedDocuments && result.acceptedDocuments.length > 0) {
      const accepted = result.acceptedDocuments[0];
      await invoice.update({
        status: 'Submitted',
        lhdn_uuid: accepted.uuid,
        lhdn_long_id: accepted.longId,
        lhdn_submission_uid: result.submissionUID,
        lhdn_submitted_at: new Date()
      });

      // Notify admin
      notificationService.createNotification(
        invoice.created_by, req.user.company_id,
        'invoice_submitted',
        'Invoice Submitted to LHDN',
        `Invoice ${invoice.invoice_number} has been submitted to LHDN for validation.`,
        { invoice_id: invoice.public_id }
      );

      auditService.log({
        action: 'invoice_submitted_lhdn',
        userId: req.user.id,
        companyId: req.user.company_id,
        targetType: 'Invoice',
        targetId: invoice.id,
        details: { invoice_number: invoice.invoice_number, lhdn_uuid: accepted.uuid }
      });

      res.json({ success: true, message: 'Invoice submitted to LHDN successfully', data: invoice });
    } else {
      // Rejected at submission
      const rejected = result.rejectedDocuments?.[0];
      await invoice.update({
        status: 'Invalid',
        lhdn_validation_errors: rejected?.error?.details || [{ message: rejected?.error?.message || 'Submission rejected' }]
      });

      res.json({
        success: false,
        message: 'Invoice was rejected by LHDN',
        data: invoice,
        errors: rejected?.error?.details || []
      });
    }
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/invoices/:id/lhdn-status — Poll LHDN for status update
 */
const checkLhdnStatus = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id }
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    if (!invoice.lhdn_uuid) {
      return res.status(400).json({ success: false, message: 'Invoice has not been submitted to LHDN' });
    }

    if (!['Submitted'].includes(invoice.status)) {
      return res.json({ success: true, message: `Invoice already in ${invoice.status} status`, data: invoice });
    }

    const result = await lhdnService.getDocumentStatus(invoice.lhdn_uuid);

    if (result.status === 'Valid') {
      const qrUrl = `https://myinvois.hasil.gov.my/${invoice.lhdn_uuid}/share/${invoice.lhdn_long_id}`;
      await invoice.update({
        status: 'Valid',
        lhdn_status: 'Valid',
        lhdn_validated_at: result.dateTimeValidated || new Date(),
        lhdn_qr_url: qrUrl
      });

      notificationService.createNotification(
        invoice.created_by, req.user.company_id,
        'invoice_validated',
        'Invoice Validated by LHDN',
        `Invoice ${invoice.invoice_number} has been validated by LHDN.`,
        { invoice_id: invoice.public_id }
      );
    } else if (result.status === 'Invalid') {
      const errors = result.validationResults?.validationSteps?.map(s => ({
        code: s.error?.code,
        message: s.error?.message,
        name: s.name
      })) || [];

      await invoice.update({
        status: 'Invalid',
        lhdn_status: 'Invalid',
        lhdn_validation_errors: errors
      });

      notificationService.createNotification(
        invoice.created_by, req.user.company_id,
        'invoice_rejected',
        'Invoice Rejected by LHDN',
        `Invoice ${invoice.invoice_number} was rejected by LHDN. Please review and fix the errors.`,
        { invoice_id: invoice.public_id, errors }
      );
    }

    res.json({ success: true, data: invoice });
  } catch (error) {
    next(error);
  }
};

/**
 * PATCH /api/invoices/:id/cancel — Valid → Cancelled
 */
const cancelInvoice = async (req, res, next) => {
  try {
    const { reason } = req.body;
    if (!reason) {
      return res.status(400).json({ success: false, message: 'Cancellation reason is required' });
    }

    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id }
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    if (invoice.status !== 'Valid') {
      return res.status(400).json({ success: false, message: 'Only Valid invoices can be cancelled' });
    }

    // Check 72-hour window
    if (invoice.lhdn_validated_at) {
      const hoursSinceValidation = (Date.now() - new Date(invoice.lhdn_validated_at).getTime()) / (1000 * 60 * 60);
      if (hoursSinceValidation > 72) {
        return res.status(400).json({
          success: false,
          message: 'Cannot cancel invoice after 72 hours of validation. Please issue a Credit Note instead.'
        });
      }
    }

    // Cancel with LHDN if it has UUID
    if (invoice.lhdn_uuid) {
      await lhdnService.cancelDocument(invoice.lhdn_uuid, reason);
    }

    await invoice.update({
      status: 'Cancelled',
      lhdn_status: 'Cancelled',
      cancelled_by: req.user.id,
      cancelled_at: new Date(),
      cancellation_reason: reason
    });

    notificationService.createNotification(
      invoice.created_by, req.user.company_id,
      'invoice_cancelled',
      'Invoice Cancelled',
      `Invoice ${invoice.invoice_number} has been cancelled. Reason: ${reason}`,
      { invoice_id: invoice.public_id }
    );

    auditService.log({
      action: 'invoice_cancelled',
      userId: req.user.id,
      companyId: req.user.company_id,
      targetType: 'Invoice',
      targetId: invoice.id,
      details: { invoice_number: invoice.invoice_number, reason }
    });

    res.json({ success: true, message: 'Invoice cancelled successfully', data: invoice });
  } catch (error) {
    next(error);
  }
};

// ─── Payments ──────────────────────────────────────────────────

/**
 * POST /api/invoices/:id/payments — Record a payment
 */
const recordPayment = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id }
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    if (!['Valid', 'Pending', 'Submitted'].includes(invoice.status)) {
      return res.status(400).json({ success: false, message: 'Payments can only be recorded for Valid/Pending/Submitted invoices' });
    }

    const { payment_date, amount, payment_method, reference_number, notes } = req.body;
    const paymentAmount = parseFloat(amount);

    if (paymentAmount <= 0) {
      return res.status(400).json({ success: false, message: 'Payment amount must be greater than 0' });
    }

    if (paymentAmount > parseFloat(invoice.balance_due)) {
      return res.status(400).json({ success: false, message: 'Payment amount exceeds balance due' });
    }

    const payment = await InvoicePayment.create({
      invoice_id: invoice.id,
      payment_date,
      amount: paymentAmount,
      payment_method,
      reference_number,
      notes,
      created_by: req.user.id
    });

    const newPaid = parseFloat(invoice.amount_paid) + paymentAmount;
    await invoice.update({
      amount_paid: parseFloat(newPaid.toFixed(2)),
      balance_due: parseFloat((parseFloat(invoice.total_amount) - newPaid).toFixed(2))
    });

    res.status(201).json({ success: true, message: 'Payment recorded successfully', data: payment });
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/invoices/:id/payments — List payments for an invoice
 */
const getPayments = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id }
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    const payments = await InvoicePayment.findAll({
      where: { invoice_id: invoice.id },
      include: [{ model: User, as: 'recorder', attributes: ['id', 'email'] }],
      order: [['payment_date', 'DESC']]
    });

    res.json({ success: true, data: payments });
  } catch (error) {
    next(error);
  }
};

/**
 * DELETE /api/invoices/:id/payments/:paymentId — Remove a payment
 */
const deletePayment = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id }
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    const payment = await InvoicePayment.findOne({
      where: { id: req.params.paymentId, invoice_id: invoice.id }
    });

    if (!payment) {
      return res.status(404).json({ success: false, message: 'Payment not found' });
    }

    const paymentAmount = parseFloat(payment.amount);
    await payment.destroy();

    const newPaid = parseFloat(invoice.amount_paid) - paymentAmount;
    await invoice.update({
      amount_paid: parseFloat(Math.max(0, newPaid).toFixed(2)),
      balance_due: parseFloat((parseFloat(invoice.total_amount) - Math.max(0, newPaid)).toFixed(2))
    });

    res.json({ success: true, message: 'Payment removed successfully' });
  } catch (error) {
    next(error);
  }
};

// ─── Generation & Utilities ────────────────────────────────────

/**
 * GET /api/invoices/:id/pdf — Download invoice PDF
 */
const downloadPdf = async (req, res, next) => {
  try {
    const invoice = await Invoice.findOne({
      where: { public_id: req.params.id, company_id: req.user.company_id },
      include: [
        { model: InvoiceItem, as: 'items' },
        { model: InvoicePayment, as: 'payments' }
      ]
    });

    if (!invoice) {
      return res.status(404).json({ success: false, message: 'Invoice not found' });
    }

    const pdfBuffer = await invoicePdfService.generatePdf(
      invoice.toJSON(),
      invoice.items.map(i => i.toJSON()),
      invoice.payments.map(p => p.toJSON())
    );

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${invoice.invoice_number}.pdf"`);
    res.setHeader('Content-Length', pdfBuffer.length);
    res.send(pdfBuffer);
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/invoices/analytics — Dashboard analytics
 */
const getAnalytics = async (req, res, next) => {
  try {
    const analytics = await invoiceService.getAnalytics(req.user.company_id);
    res.json({ success: true, data: analytics });
  } catch (error) {
    next(error);
  }
};

/**
 * POST /api/invoices/generate/payroll — Auto-create from payroll
 */
const generateFromPayroll = async (req, res, next) => {
  try {
    const { payroll_id } = req.body;

    // Look up payroll by public_id
    const payroll = await Payroll.findOne({ where: { public_id: payroll_id } });
    if (!payroll) {
      return res.status(404).json({ success: false, message: 'Payroll record not found' });
    }

    const invoice = await invoiceService.generateFromPayroll(payroll.id, req.user.company_id, req.user.id);
    res.status(201).json({ success: true, message: 'Invoice generated from payroll', data: invoice });
  } catch (error) {
    if (error.message.includes('already exists') || error.message.includes('must be')) {
      return res.status(400).json({ success: false, message: error.message });
    }
    next(error);
  }
};

/**
 * POST /api/invoices/generate/claim — Auto-create from claim
 */
const generateFromClaim = async (req, res, next) => {
  try {
    const { claim_id } = req.body;

    const claim = await Claim.findOne({ where: { public_id: claim_id } });
    if (!claim) {
      return res.status(404).json({ success: false, message: 'Claim record not found' });
    }

    const invoice = await invoiceService.generateFromClaim(claim.id, req.user.company_id, req.user.id);
    res.status(201).json({ success: true, message: 'Invoice generated from claim', data: invoice });
  } catch (error) {
    if (error.message.includes('already exists') || error.message.includes('must be')) {
      return res.status(400).json({ success: false, message: error.message });
    }
    next(error);
  }
};

/**
 * POST /api/invoices/bulk-submit — Batch submit to LHDN
 */
const bulkSubmitToLhdn = async (req, res, next) => {
  try {
    const { invoice_ids } = req.body;
    if (!invoice_ids || invoice_ids.length === 0) {
      return res.status(400).json({ success: false, message: 'No invoice IDs provided' });
    }

    const invoices = await Invoice.findAll({
      where: {
        public_id: { [Op.in]: invoice_ids },
        company_id: req.user.company_id,
        status: 'Pending'
      },
      include: [{ model: InvoiceItem, as: 'items' }]
    });

    const results = { accepted: [], rejected: [], skipped: [] };

    for (const invoice of invoices) {
      try {
        const result = await lhdnService.submitDocument(invoice.toJSON(), invoice.items.map(i => i.toJSON()));

        if (result.acceptedDocuments?.length > 0) {
          const accepted = result.acceptedDocuments[0];
          await invoice.update({
            status: 'Submitted',
            lhdn_uuid: accepted.uuid,
            lhdn_long_id: accepted.longId,
            lhdn_submission_uid: result.submissionUID,
            lhdn_submitted_at: new Date()
          });
          results.accepted.push(invoice.invoice_number);
        } else {
          const rejected = result.rejectedDocuments?.[0];
          await invoice.update({
            status: 'Invalid',
            lhdn_validation_errors: rejected?.error?.details || []
          });
          results.rejected.push({ invoice_number: invoice.invoice_number, errors: rejected?.error?.details });
        }
      } catch (err) {
        results.skipped.push({ invoice_number: invoice.invoice_number, error: err.message });
      }
    }

    const skippedIds = invoice_ids.length - invoices.length;
    if (skippedIds > 0) {
      results.skipped.push({ message: `${skippedIds} invoice(s) were not in Pending status` });
    }

    res.json({
      success: true,
      message: `Bulk submission complete: ${results.accepted.length} accepted, ${results.rejected.length} rejected, ${results.skipped.length} skipped`,
      data: results
    });
  } catch (error) {
    next(error);
  }
};

/**
 * POST /api/invoices/validate-tin — Validate a TIN number
 */
const validateTin = async (req, res, next) => {
  try {
    const { tin } = req.body;
    if (!tin) {
      return res.status(400).json({ success: false, message: 'TIN is required' });
    }

    const result = await lhdnService.validateTIN(tin);
    res.json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};

// ─── AI Extraction ─────────────────────────────────────────────

// Normalize a company/person name for comparison: lowercase, drop common suffixes,
// strip non-alphanumeric. Used to compare extracted buyer vs project.client_name.
function normalizeName(name) {
  if (!name) return '';
  return String(name)
    .toLowerCase()
    .replace(/\bsdn\.?\s*bhd\.?\b/g, '')
    .replace(/\bbhd\.?\b/g, '')
    .replace(/\bpte\.?\s*ltd\.?\b/g, '')
    .replace(/\bltd\.?\b/g, '')
    .replace(/\binc\.?\b/g, '')
    .replace(/\(m\)/g, '')
    .replace(/[^a-z0-9]+/g, '');
}

// Collect every distinct PO candidate to try matching against projects.
// Includes the whole raw string (single POs with internal separators like
// "AEM/BD/PO/25/006") plus split fragments (multi-PO joins like
// "PO-001/PO-002"). The lookup downstream prefers whole-string matches over
// fragment matches — see expandPoFragments.
function collectPoNumbers(extracted) {
  const set = new Set();
  const add = (raw) => {
    expandPoFragments(raw).forEach(c => set.add(c));
  };
  add(extracted?.po_number);
  if (Array.isArray(extracted?.items)) {
    for (const it of extracted.items) add(it?.po_number);
  }
  return Array.from(set);
}

/**
 * Look up every PO referenced on the invoice and compare each project's
 * client_name against the extracted buyer. Auto-link is only viable when
 * exactly one project covers all POs AND its recipient matches.
 */
async function checkPoMatch(extracted, companyId) {
  // Collect distinct RAW PO strings (header + items), no splitting yet.
  const rawPoSet = new Set();
  const addRaw = (raw) => {
    const t = String(raw || '').trim();
    if (t) rawPoSet.add(t);
  };
  addRaw(extracted?.po_number);
  if (Array.isArray(extracted?.items)) {
    for (const it of extracted.items) addRaw(it?.po_number);
  }
  if (rawPoSet.size === 0) return { found: false, matches: [], multi_po: false };

  const lookup = await buildPoLookupMap(companyId);
  const extractedBuyer = extracted.buyer_name || '';
  const matches = [];
  const seen = new Set();

  for (const raw of rawPoSet) {
    const candidates = expandPoFragments(raw);
    let resolvedAny = false;

    for (const candidate of candidates) {
      const project = lookup.get(candidate.trim().toLowerCase());
      if (!project) continue;
      if (seen.has(candidate)) { resolvedAny = true; continue; }
      seen.add(candidate);
      matches.push({
        po_number: candidate,
        project: {
          id: project.id,
          public_id: project.public_id,
          code: project.code,
          name: project.name,
          client_name: project.client_name,
          po_number: project.po_number,
          currency: project.currency
        },
        recipient_match: !!project.client_name &&
          normalizeName(extractedBuyer) === normalizeName(project.client_name)
      });
      resolvedAny = true;
      // If the whole raw string matched, don't also report its fragments —
      // would just be noise (e.g. "AEM/BD/PO/25/006" matched, skip "AEM" etc.)
      if (candidate === raw) break;
    }

    if (!resolvedAny && !seen.has(raw)) {
      // Nothing in this raw resolved — record as not-found
      seen.add(raw);
      matches.push({ po_number: raw, project: null, recipient_match: false });
    }
  }

  const hits = matches.filter(m => m.project);
  const uniqueProjectIds = new Set(hits.map(m => m.project.id));
  const singleProject = uniqueProjectIds.size === 1;
  const recipientMatchAll = hits.length > 0 && hits.every(m => m.recipient_match);

  return {
    found: hits.length > 0,
    matches,
    multi_po: hits.length > 1 || rawPoSet.size > 1,
    single_project: singleProject,
    recipient_match: recipientMatchAll && singleProject,
    project: singleProject && hits.length > 0 ? hits[0].project : undefined,
    extracted_buyer_name: extractedBuyer,
    project_client_name: singleProject && hits.length > 0 ? hits[0].project.client_name : null,
    searched_pos: [...rawPoSet]
  };
}

/**
 * POST /api/invoices/extract-from-pdf
 * Accepts a single PDF, returns extracted invoice data (does NOT create the invoice).
 * User reviews + edits in the form dialog, then submits via the normal create flow.
 */
const extractFromPdf = async (req, res, next) => {
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, message: 'No PDF file provided' });
    }
    if (req.file.mimetype !== 'application/pdf') {
      return res.status(400).json({ success: false, message: 'Only PDF files are supported' });
    }

    const { extracted, usage, provider } = await invoiceExtractionService.extractInvoiceFromPdf(
      req.file.buffer,
      req.file.originalname,
      { provider: req.body.provider }
    );

    const poMatch = await checkPoMatch(extracted, req.user.company_id);

    res.json({
      success: true,
      message: 'Document extracted successfully',
      data: {
        extracted,
        filename: req.file.originalname,
        usage,
        provider,
        po_match: poMatch
      }
    });
  } catch (error) {
    logger.error('PDF extraction failed', { error: error.message, filename: req.file?.originalname });
    next(error);
  }
};

/**
 * Map an extracted-invoice payload (matching the extraction tool schema)
 * into the shape the createInvoice flow expects.
 */
function mapExtractedToInvoicePayload(extracted, { asRecorded = true } = {}) {
  const items = (extracted.items || []).map(it => ({
    description: it.description || '',
    quantity: Number(it.quantity) || 1,
    unit_price: Number(it.unit_price) || 0,
    discount_amount: Number(it.discount_amount) || 0,
    discount_rate: 0,
    tax_type: it.tax_type || 'Exempt',
    tax_rate: Number(it.tax_rate) || 0,
    unit_of_measurement: it.unit_of_measurement || 'EA',
    classification_code: it.classification_code || null,
    po_number: it.po_number || null
  }));

  return {
    invoice_number: extracted.invoice_number || null,
    invoice_type: extracted.invoice_type || '01',
    is_self_billed: !!extracted.is_self_billed,
    invoice_date: extracted.invoice_date || new Date().toISOString().slice(0, 10),
    due_date: extracted.due_date || null,
    commence_date_start: extracted.commence_date_start || null,
    commence_date_end: extracted.commence_date_end || null,
    payment_terms: extracted.payment_terms || null,
    currency: extracted.currency || 'MYR',
    title: extracted.title || null,
    notes: extracted.notes || null,
    supplier_name: extracted.supplier_name || 'Unknown Supplier',
    supplier_tin: extracted.supplier_tin || null,
    supplier_brn: extracted.supplier_brn || null,
    supplier_sst_no: extracted.supplier_sst_no || null,
    supplier_msic_code: extracted.supplier_msic_code || null,
    supplier_address: extracted.supplier_address || null,
    supplier_phone: extracted.supplier_phone || null,
    supplier_email: extracted.supplier_email || null,
    buyer_name: extracted.buyer_name || 'Unknown Buyer',
    buyer_tin: extracted.buyer_tin || null,
    buyer_brn: extracted.buyer_brn || null,
    buyer_address: extracted.buyer_address || null,
    buyer_phone: extracted.buyer_phone || null,
    buyer_email: extracted.buyer_email || null,
    status: asRecorded ? 'Recorded' : 'Draft',
    items
  };
}

/**
 * POST /api/invoices/bulk-import
 * Accepts multiple PDFs, extracts each, creates an invoice per file.
 * Defaults to status "Recorded" — typical use case is logging old/historical invoices.
 */
const bulkImport = async (req, res, next) => {
  try {
    if (!req.files || req.files.length === 0) {
      return res.status(400).json({ success: false, message: 'No PDF files provided' });
    }

    const asRecorded = req.body.as_recorded === undefined ? true : req.body.as_recorded === 'true' || req.body.as_recorded === true;
    const provider = req.body.provider;
    const companyId = req.user.company_id;
    const userId = req.user.id;

    const results = { created: [], failed: [] };

    // Process sequentially to keep concurrent Anthropic + DB load predictable.
    // For larger batches a concurrency-limited pool would be the next step.
    for (const file of req.files) {
      try {
        if (file.mimetype !== 'application/pdf') {
          results.failed.push({ filename: file.originalname, error: 'Not a PDF file' });
          continue;
        }

        const { extracted } = await invoiceExtractionService.extractInvoiceFromPdf(file.buffer, file.originalname, { provider });
        const payload = mapExtractedToInvoicePayload(extracted, { asRecorded });

        // Mirror createInvoice() — use extracted number if unique, else auto-gen.
        const { invoiceNumber } = await resolveInvoiceNumber(payload.invoice_number, companyId);
        delete payload.invoice_number;
        const calculatedItems = payload.items.map((item, idx) =>
          invoiceService.calculateItemTotals({ ...item, item_number: idx + 1 })
        );
        const totals = invoiceService.calculateInvoiceTotals(calculatedItems);

        let itemsWithProjects = await attachItemProjectIds(calculatedItems, companyId);
        if (!payload.project_id) {
          const firstItemProjectId = itemsWithProjects.find(it => it.project_id)?.project_id;
          if (firstItemProjectId) payload.project_id = firstItemProjectId;
        }
        itemsWithProjects = inheritInvoiceProjectIdToItems(itemsWithProjects, payload.project_id);

        const invoice = await Invoice.create({
          ...payload,
          company_id: companyId,
          invoice_number: invoiceNumber,
          ...totals,
          balance_due: totals.total_amount,
          source_type: 'manual',
          created_by: userId
        });

        await InvoiceItem.bulkCreate(
          itemsWithProjects.map(item => ({ ...item, invoice_id: invoice.id }))
        );

        results.created.push({
          filename: file.originalname,
          public_id: invoice.public_id,
          invoice_number: invoice.invoice_number,
          title: invoice.title,
          total_amount: invoice.total_amount,
          confidence: extracted.confidence,
          extraction_notes: extracted.extraction_notes || []
        });
      } catch (err) {
        logger.error('Bulk import item failed', { filename: file.originalname, error: err.message });
        results.failed.push({ filename: file.originalname, error: err.message });
      }
    }

    res.json({
      success: true,
      message: `Imported ${results.created.length} of ${req.files.length} files`,
      data: results
    });
  } catch (error) {
    next(error);
  }
};

/**
 * POST /api/invoices/bulk-extract
 * Extract a batch of PDFs and return the structured data per file.
 * Does NOT write to the DB — the frontend renders the results for review,
 * then calls bulk-create with the (possibly edited) data.
 */
const bulkExtract = async (req, res, next) => {
  try {
    if (!req.files || req.files.length === 0) {
      return res.status(400).json({ success: false, message: 'No PDF files provided' });
    }

    const provider = req.body.provider;
    const companyId = req.user.company_id;
    const results = [];

    for (const file of req.files) {
      try {
        if (file.mimetype !== 'application/pdf') {
          results.push({ filename: file.originalname, error: 'Not a PDF file' });
          continue;
        }

        const { extracted, usage } = await invoiceExtractionService.extractInvoiceFromPdf(
          file.buffer,
          file.originalname,
          { provider }
        );

        const poMatch = await checkPoMatch(extracted, companyId);

        results.push({
          filename: file.originalname,
          extracted,
          po_match: poMatch,
          usage
        });
      } catch (err) {
        logger.error('Bulk extract item failed', { filename: file.originalname, error: err.message });
        results.push({ filename: file.originalname, error: err.message });
      }
    }

    res.json({
      success: true,
      message: `Extracted ${results.filter(r => !r.error).length} of ${req.files.length} files`,
      data: { results }
    });
  } catch (error) {
    next(error);
  }
};

/**
 * POST /api/invoices/bulk-create
 * Create invoices from an array of reviewed/edited extracted-data payloads.
 * Frontend sends:
 *   {
 *     as_recorded: boolean,
 *     items: [
 *       { extracted, filename, project_id? },
 *       ...
 *     ]
 *   }
 */
const bulkCreate = async (req, res, next) => {
  try {
    const { items, as_recorded } = req.body;
    if (!Array.isArray(items) || items.length === 0) {
      return res.status(400).json({ success: false, message: 'No items to create' });
    }

    const asRecorded = as_recorded === undefined ? true : as_recorded === 'true' || as_recorded === true;
    const companyId = req.user.company_id;
    const userId = req.user.id;
    const results = { created: [], failed: [] };

    for (const item of items) {
      const filename = item.filename || 'unknown.pdf';
      try {
        if (!item.extracted) {
          results.failed.push({ filename, error: 'Missing extracted data' });
          continue;
        }

        const payload = mapExtractedToInvoicePayload(item.extracted, { asRecorded });
        if (item.project_id) payload.project_id = item.project_id;

        const { invoiceNumber } = await resolveInvoiceNumber(payload.invoice_number, companyId);
        delete payload.invoice_number;
        const calculatedItems = payload.items.map((it, idx) =>
          invoiceService.calculateItemTotals({ ...it, item_number: idx + 1 })
        );
        const totals = invoiceService.calculateInvoiceTotals(calculatedItems);

        let itemsWithProjects = await attachItemProjectIds(calculatedItems, companyId);
        if (!payload.project_id) {
          const firstItemProjectId = itemsWithProjects.find(it => it.project_id)?.project_id;
          if (firstItemProjectId) payload.project_id = firstItemProjectId;
        }
        itemsWithProjects = inheritInvoiceProjectIdToItems(itemsWithProjects, payload.project_id);

        const invoice = await Invoice.create({
          ...payload,
          company_id: companyId,
          invoice_number: invoiceNumber,
          ...totals,
          balance_due: totals.total_amount,
          source_type: 'manual',
          created_by: userId
        });

        await InvoiceItem.bulkCreate(
          itemsWithProjects.map(it => ({ ...it, invoice_id: invoice.id }))
        );

        results.created.push({
          filename,
          public_id: invoice.public_id,
          invoice_number: invoice.invoice_number,
          title: invoice.title,
          total_amount: invoice.total_amount,
          confidence: item.extracted.confidence,
          extraction_notes: item.extracted.extraction_notes || []
        });
      } catch (err) {
        logger.error('Bulk create item failed', { filename, error: err.message });
        results.failed.push({ filename, error: err.message });
      }
    }

    res.json({
      success: true,
      message: `Created ${results.created.length} of ${items.length} invoices`,
      data: results
    });
  } catch (error) {
    next(error);
  }
};

module.exports = {
  createInvoice,
  getAllInvoices,
  getInvoiceById,
  updateInvoice,
  deleteInvoice,
  bulkDelete,
  approveInvoice,
  submitToLhdn,
  checkLhdnStatus,
  cancelInvoice,
  recordPayment,
  getPayments,
  deletePayment,
  downloadPdf,
  getAnalytics,
  generateFromPayroll,
  generateFromClaim,
  bulkSubmitToLhdn,
  validateTin,
  extractFromPdf,
  bulkImport,
  bulkExtract,
  bulkCreate
};
